piVersion: apps/v1
kind: Deployment
metadata:
 name: app
 labels:
   app: e-comm-web
spec:
 replicas: 3
 selector:
  matchLabels:  
   app: e-comm-web
 template:
  metadata:
   labels:
     app: e-comm-web

  spec:
   containers:
    - name: e-comm-webapp
      image: vinod0510/e-commerce
      ports:
       - containerPort: 80
